# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b982396d7c2aacd85392cd0550385052451cb07b520990e01d5f7c3e38893f3496fe6c138322b044bf6ebcefaf7ac0e48be8101b94c13230e8bb1b36988d5d

test:
  secret_key_base: 921b8b4c0944bee860e4659a5d70dcf13490318d0964d5203e7965f2eec8ee09c5d9510e69c589d12793ab10bba0f753a229d95f189464991e68d0abd36fe76c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
